node{
    stage('SCM Checkout'){
      git 'https://github.com/Surajgupta5/Maven'
      }
      stage('COmpile-Package'){
        def mvnHome = tool name: 'maven-3', type: 'maven'
        sh 'mvn package'
       }
  
}
